spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/db_shiro
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.hausen.shiro.beans
